### ISSUE TITLE
not work for me

### ISSUE THREAD

**Issue by Schneideisen** [underweba/devfeeinterceptor#2]
I start  Inspector and its wait on "[2/4] Please start PhoenixMiner now to detect your wallet."

I start "Phoenix Miner 5.5c Windows/msvc - Release build" 

But the Inspector do nothing

i used "-pool eu1.ethermine.org:14444" this is non ssl

**Comment by underweba** [comment]
The addon will detecte phoenixminer wallet once it connects to the pool.
Do you have any strict firewall or antivirus installed that might be blocking the packet detection?
Release 1.1 was extensively tested against PhoenixMiner 5.5c. Please send me the txt log so I can analyse it.
Thank you

**Comment by 418451** [comment]
i used "-pool eth-pool.beepool.org:9530",not work for me

06.05.2021 00:05:06
[1/4] NoDevFee successfuly initialized.
[2/4] Please start PhoenixMiner now to detect your wallet.
[3/4] PhoenixMiner initialized. Detecting your wallet...
Your NoDevFee Wallet: 0x^^^^^^^^^^

Waiting for the next DevFee mining...

06.05.2021 00:40:49
Wallet intercepted!
DevFeeWallet: 0x00d4405692b9F4f2Eb9E99Aee053aF257c521343
NoDevFeeWallet: 0x^^^^^^^^^^

**Comment by 418451** [comment]
No eth1.0 worker found.

**Comment by 418451** [comment]
PhoenixMiner_5.5c_Windows

**Comment by Schneideisen** [comment]
06.05.2021 03:55:47
[1/4] NoDevFee successfuly initialized.
[2/4] Please start PhoenixMiner now to detect your wallet.-----------------------------------------------------------------------------------------
                                  PhoenixMiner DevFee interceptor 1.1
-----------------------------------------------------------------------------------------
06.05.2021 04:08:25
[1/4] NoDevFee successfuly initialized.
[2/4] Please start PhoenixMiner now to detect your wallet.

**Comment by Schneideisen** [comment]
[log.txt](https://github.com/underweba/devfeeinterceptor/files/6431368/log.txt)

**Comment by Schneideisen** [comment]
no firewall / windowsdefender activ

**Comment by 418451** [comment]
thanks.
Successfully intercepted devfee.

**Comment by underweba** [comment]
Glad to know it is solved.

**Comment by proepkes** [comment]
For me the interceptor is stuck at "[2/4] Please start PhoenixMiner now to detect your wallet.". I run PhoenixMiner 5.5c with:
* -pool eu1.ethermine.org:4444
* -wal 0xmyaddress.workername
* -proto 3

DevFree however connects with ssl to port 5555 even though I've passed port 4444 in the parameter
