### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by intel5** [underweba/devfeeinterceptor#4]
2021.05.08:01:31:48.555: main DevFee: Connecting to ethash pool ssl://asia1.ethermine.org:5555 (proto: EthProxy)
2021.05.08:01:31:48.568: edev DevFee: Connected to SSL ethash pool asia1.ethermine.org:5555 (172.65.231.156)
2021.05.08:01:31:48.676: edev DevFee: New job #1d10474a from ssl://asia1.ethermine.org:5555; diff: 4295MH
2021.05.08:01:31:49.498: edev DevFee: New job #650b6044 from ssl://asia1.ethermine.org:5555; diff: 4295MH

It seems that ssl is used unconditionally in the Ethermine pool
So it doesn't work.

**Comment by underweba** [comment]
Is **does** work with Ethermine.
You need to specify the port and protocol.
Use stratum port 4444 instead of 5555 (which is SSL) and remote the SSL part from the provided pool URL
example: `asia1.ethermine.org:4444`
